# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input Link'
        # Default value if no value is explicitly provided
        default: 'https://ourmoment.my.id/art-6'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      - name: Set Payload on Redis CLI
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export VPS_APP_PATH=~/app/gowebcapture
            export IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/gowebcapture

            echo "Path       : $VPS_APP_PATH"
            echo "IMAGE_NAME : $IMAGE_NAME"

            cd $VPS_APP_PATH

            echo "Pushing to Redis queue..."
            docker exec redis_svc redis-cli -a "${{ secrets.REDIS_AUTH_PASS }}" LPUSH video_queue "${{ github.event.inputs.name }}"

            echo "✅ Pushed to queue. Waiting 3 minutes for processing..."
            sleep 180

            echo "🧾 Container logs:"
            docker logs gowebcapture-gowebcapture-1 || echo "Logs not found"

            echo "📂 Generated videos:"
            ls ./output || echo "Output directory not found"
