name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo $DOCKER_PASSWORD >> secrets.txt
          echo $DOCKER_USERNAME >> secrets.txt
          echo $GH_TOKEN >> secrets.txt
          echo SSH_PASSPHRASE >> secrets.txt
          echo $SSH_PRIVATE_KEY >> secrets.txt
          scp secrets.txt ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/app/
        shell: bash
